#
# Redis Dockerfile
#
# https://github.com/dockerfile/redis
#

# Pull base image.
FROM raychorn/ubuntu_focal_all_pythons:latest


# Define default command.
#CMD ["redis-server", "/etc/redis/redis.conf"]

# Expose ports.
#EXPOSE 6379